[env:lptm4c1294ncpdt]
platform = titiva
board = lptm4c1294ncpdt
board_build.ldscript = src/platformio_linker.ld

build_flags =
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp

    -I C:/ti/TivaWare_C_Series-2.2.0.295
    -I C:/ti/TivaWare_C_Series-2.2.0.295/third_party/FreeRTOS/Source/include
    -I C:/ti/TivaWare_C_Series-2.2.0.295/third_party/FreeRTOS/Source/portable/GCC/ARM_CM4F

    -I lib/grlib
    -Wl,--entry=ResetISR
    -O3
    -DPART_TM4C1294NCPDT
    -DTARGET_IS_TM4C129_RA2
    


lib_deps = 
    grlib
    
src_filter = +<*> -<.git/>