[env:lptm4c1294ncpdt]
platform = titiva
board = lptm4c1294ncpdt
board_build.ldscript = src/grlib_demo.ld

build_flags =
   -mfpu=fpv4-sp-d16
   -mfloat-abi=softfp
   -I /ti/TivaWare_C_Series-2.2.0.295
   -I /ti/TivaWare_C_Series-2.2.0.295/third_party/FreeRTOS/include
   -I /ti/TivaWare_C_Series-2.2.0.295/third_party/FreeRTOS/portable/GCC/ARM_CM4F
   -Wl,--entry=ResetISR
   -O3
   -DPART_TM4C1294NCPDT
   -DTARGET_IS_TM4C129_RA2
   -Lsrc