[env:lptm4c1294ncpdt]
platform = titiva
board = lptm4c1294ncpdt
board_build.ldscript = src/platformio_linker.ld

build_flags =
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    ; Tell the compiler where to find the TivaWare headers on your system
    -I /ti/TivaWare_C_Series-2.2.0.295
    -I /ti/TivaWare_C_Series-2.2.0.295/third_party/FreeRTOS/include
    -I /ti/TivaWare_C_Series-2.2.0.295/third_party/FreeRTOS/portable/GCC/ARM_CM4F
    ; Tell the compiler to look in your project's local grlib folder
    -I lib/grlib
    -Wl,--entry=ResetISR
    -O3
    -DPART_TM4C1294NCPDT
    -DTARGET_IS_TM4C129_RA2
    

; This is the "magic" line that helps PlatformIO find dependencies in /lib
lib_deps = 
    grlib

src_filter = +<*> -<.git/>